---
- name:  this playbook for backup demo
  hosts: localhost
  become_user: root
  tasks: 
    - name: backup file with rsync 
      ansible.builtin.synchronize:
        src: /tmp/testfile.txt
        dest: /tmp/test
        mode: pull
