---
- name: pause module demo
  hosts: localhost
  become_user: root
  vars: 
    wait_seconds: 10
  tasks:
    - name: pause for {{ wait_seconds | int }} seconds(s)
      ansible.builtin.pause:
        seconds: "{{ wait_seconds | int }}"

    - name: print message
      ansible.builtin.debug:
        msg: "pause demo"
  
