---
- name:  this playbook is demo for get url modules
  hosts: localhost
  become_user: root
  tasks: 
    - name: downlaod tomcat from webhost
      ansible.builtin.get_url: 
        url: https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.2/bin/apache-tomcat-11.0.2.tar.gz
        dest: /tmp/test
        mode: 0755
    - name: unarchive the tomcat 
      ansible.builtin.unarchive: 
        src: /tmp/test/apache-tomcat-11.0.2.tar.gz
        dest: /tmp/test
        mode: 0755
