---
- name: install multiple packages
  hosts: localhost
  become_user: root
  tasks:
    - name: install packages
      community.general.apk::
        update_cache: yes
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - wget
