---
- name: command module demo
  hosts: all
  become: true
  tasks:
    - name: check server uptime
      ansible.builtin.command: uptime
      register: coomand_output
    - name: command output
      ansible.builtin.debug:
        var: command_output.stdout_lines