---
- name: debug module demo
  hosts: localhost
  become: true
  vars:
    fruit: " Apple"
  tasks:
    - name: debug messages 
      ansible.builtin.debug: 
        msg: " our fruit is {{ fruit }}" 
