- name: install git using ansible
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: install git
      yum:
        name: git
        state: present
    - name: print git version
      command: git --version
      register: git_version
    - name: print git version
      debug:
        var: git_version.stdout

