---
- name: this is for installing httpd
  hosts: localhost
  become: true
    #gather_facts: no
  tasks:
    - name: install httpd
      ansible.builtin.apt:
        name: apache2
        state: present

      notify: start the apache2 service

  handlers:

    - name: start the apache2 service
      ansible.builtin.service:
        name: apache2
        state: started

