---
- name: this is for installing httpd
  hosts: localhost
  become: true
  tasks:
    - name: install httpd
      ansible.builtin.apt:
        name: apache2
        state: present
      tags: tag1

    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: apache2
        state: started
      tags: tag2

    - name: Enable service httpd, and not touch the state
      ansible.builtin.service:
        name: apache2
        enabled: yes
      tags: tag3

    - name: Enable service httpd, and not touch the state
      ansible.builtin.service:
        name: apache2
        state: stopped
      tags: tag4
      
    - name: uninstall the apache2
      ansible.builtin.apt:
        name: apache2
        state: absent
      tags: tag5
