---
- name: create user using ansible variable
  hosts: localhost
  become: true
  become_method: su
  become_user: nobody
  vars_files: 
    - user.yml
  tasks:
    - name: creating a user {{ autosys }}
      user:
        name: "{{ user }}"
