---
- name: this playbook for vault demos
  hosts: localhost
  become: true
  tasks:
    - name: include vault files
      ansible.builtin.include_vars:
        file: mypassword.yml

    - name: print mypassword value
      ansible.builtin.debug:
        var: mypassword


--- 
- name: Playbook for ansible vault
  hosts: all 
  vars: 
    mypassword: mypasswordsecrets
  tasks:
    - name: print the my password 
      ansible.builtin.debug: 
        var: mypassword
        