---
- name: install multiple packages
  hosts: localhost
  become: true
  tasks:
    - name: install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - gcc
        - make
        - gzip
        - wget
        - telnet
