---
# handlers file for apache
- name: start apache
  ansible.builtin.service:
    name: httpd
    state: started 

- name: start apache2
  ansible.builtin.service:
    name: apache2
    state: started 

- name: restart apache2
  ansible.builtin.service:
    name: httpd
    state: restarted

- name: restart apache2 
  ansible.builtin.service:
    name: apache2
    state: restarted 
