---
# tasks file for apachesetup-role
    - name: install httpd
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: copy index.html
      ansible.builtin.copy:
        src: /tmp/index.html
        dest: /var/www/html
        mode: 0666

    - name: ensure the default Apache port is {{ port }} on ubuntu
      ansible.builtin.lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen'
        insertafter: "# /ect/apache2/sites-enabled/000-default.conf"
        line: Listen {{ port }}
      notify: restart apache


